import { readdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Route discovery for the gates.
 *
 * ─────────────────────────────────────────────────────────────────
 * WHY THIS EXISTS, 2026-08-07.
 *
 * The a11y and no-JS specs used to list article routes literally:
 *
 *     '/balita/pagtatanim-ng-bakawan',
 *     '/kaganapan/medical-mission-agosto',
 *
 * Those were sample slugs, and they were correct for exactly one day. The
 * moment the site started building its articles from the CMS, the slugs became
 * whatever the barangay had typed — `bakawan-2026`, `medical-mission-2026-08`
 * — and six tests failed against pages that no longer existed.
 *
 * The tests were not wrong about what they wanted to check. They were wrong to
 * assume content is a constant. A hard-coded slug in a test is a promise that
 * a specific announcement will exist forever, which is not a promise a CMS can
 * keep — and it would have failed again the first time the barangay renamed a
 * story or unpublished one.
 *
 * So routes are DISCOVERED from what the build actually produced. The gates
 * now cover whatever articles shipped, including ones written years from now
 * by people who have never read this file.
 * ─────────────────────────────────────────────────────────────────
 */

const DIST = join(process.cwd(), 'dist')

/**
 * Article routes under a directory, as built.
 *
 * Reads the filesystem rather than the sitemap: the sitemap is generated by an
 * integration and could itself be wrong, whereas a directory containing an
 * `index.html` is the page a reader will actually be served.
 */
function builtRoutes(dir: string, limit: number): string[] {
  const base = join(DIST, dir)
  if (!existsSync(base)) return []

  return readdirSync(base, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(base, e.name, 'index.html')))
    .map((e) => `/${dir}/${e.name}`)
    .sort() // Stable ordering, so a failure names the same route on a re-run.
    .slice(0, limit)
}

/**
 * A representative sample of article pages.
 *
 * Not all of them: a barangay with two hundred announcements would otherwise
 * multiply the axe suite by two hundred, in both languages, across three
 * browser projects. Every article of a kind renders through the same view, so
 * a handful proves the template.
 *
 * Two of each kind, because one would not catch a difference between the first
 * item and the rest — and the events pair is chosen to span upcoming AND past
 * where possible, since the past variant re-colours its date tile and adds a
 * chip that only it renders.
 */
export const ARTICLE_ROUTES: string[] = [
  ...builtRoutes('balita', 2),
  ...builtRoutes('kaganapan', 2),
]
